# Generated by Django 2.2.7 on 2019-12-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economiza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('numero', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
